//
//  IACTestMessageData.h
//
//  Created by tommy zhang on 08-11-27.
//  Copyright 2008. All rights reserved.
//

#import <Cocoa/Cocoa.h>

typedef enum{
	TABLEVIEW_RELOADDATA = 1,
	TABLEVIEW_DISPLAYDATA,
	TABLEVIEW_SCROLL_ROW_TO_VISIBLE,
	TABLEVIEW_REMOVE_COLUMN_WITH_IDENTIFIER,
	
	RECORD_SENDDATA,
	RECORD_REMOVE_OBJECT_AT_INDEX,
	RECORD_INSERT_OBJECT_AT_INDEX,
	RECORD_ADD_OBJECT,
	
	SHOWTEXT,
	SENDBTN_STATE,
	TESTALLBTN_STATE,
	CLOSEBTN_STATE,
	STARTBTN_STATE,
	
	SET_WINDOW_COLOR,
	TESTDONE_SET,
	WINDOW_SETTITLE,
	
	TFUSERID_SETSTRING,
	TFGETSN_SET_SELECTABLE,//
    TFGETSN1_SET_SELECTABLE,//
	TFGETSN_STATE,
	TFGETSN_SETSTRING,
	TFGETSN_FIRST_RESPONDER,
	TFGETSN_EDITABLE,
	
	TFMLBSN_SET_SELECTABLE,//
	TFMLBSN_STATE,
    TFGETSN1_STATE,	
	TFMLBSN_SETSTRING,
	TFMLBSN_FIRST_RESPONDER,
	TFMLBSN_EDITABLE,
	
	TFFGSN_SET_SELECTABLE,//
	TFFGSN_STATE,
    TFGETSN1_SETSTRING,
    TFGETSN1_FIRST_RESPONDER,
	TFFGSN_SETSTRING,
    TFFGSN1_SETSTRING,
	TFGETSN1_EDITABLE,
	TFFGSN_FIRST_RESPONDER,
	TFFGSN_EDITABLE,
	
    TFINPUTNUMBER1_SETSTRING,
    TFINPUTNUMBER2_SETSTRING,
    
    TFUNITNUM_SET_SELECTABLE,//
	TFUNITNUM_STATE,
	TFUNITNUM_SETSTRING,
	TFUNITNUM_FIRST_RESPONDER,
	TFUNITNUM_EDITABLE,

    TFBUILDEVENT_SET_SELECTABLE,//
	TFBUILDEVENT_STATE,
	TFBUILDEVENT_SETSTRING,
	TFBUILDEVENT_FIRST_RESPONDER,
	TFBUILDEVENT_EDITABLE,
    
    BTCSPECIALBUILD_SET_SELECTABLE,
    
	TFMPN_SETSTRING,
	TFREGION_SETSTRING,
	
    TFDIAGVERSION_SETSTRING,
    TFSOFTWAREVERSION_SETSTRING,
    
	TFDBNAME_SETSTRING,
	TFSEVERNAME_SETSTRING,
	
	MODEL_SELECT_CHANGE,
	
	COMBOX_SELECT_INDEX,
    COMBOX_SELECT_ENABLE,
	COMBOX_SELECT_CHANGE,
	COMBOX_MODEL_RELOAD,
    COMBOX_DELETE_ALLITEM,
	
	//for ProcessCenterNotification
	START,
	CLOSE_PROGRAM,
	TESTALL,
	WINDOW_NEED_DATA,
	SN_UPDATE,
	SN_CHECK,
    SN1_CHECK,
    SN1_UPDATE,
	MLBSN_CHECK,
	FGSN_CHECK,
	MLBSN_UPDATE,
	FGSN_UPDATE,
	MPN_UPDATE,
	REGN_UPDATE,
	PASSWORD_UPDATE,
    SCAN_HOST,
    START_TEST
	
}EnumIACMessage;


@interface IACMessageData : NSObject {
	EnumIACMessage message;
	id idArg;
	int intArg;
	bool boolArg;
}

@property(copy,readwrite)id idArg;
@property(readwrite) EnumIACMessage message;
@property(readwrite) int intArg;
@property(readwrite) bool boolArg;

+(IACMessageData *)sendMessage: (EnumIACMessage)messageToBeSent
					IdArgument:(id)FirstArg
				   IntArgument:(int) SecondArg
				  BoolArgument:(bool) ThirdArg;
+(IACMessageData *)sendMessage:(EnumIACMessage)messageToBeSent
					IdArgument:(id)FirstArg;
+(IACMessageData *)sendMessage:(EnumIACMessage)messageToBeSent
				   IntArgument:(int)SecondArg;
+(IACMessageData *)sendMessage:(EnumIACMessage)messageToBeSent
				  BoolArgument:(bool)ThirdArg;

					

@end

